### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by elopezsa** [stanfy/behave-rest#4]
When I try run the projects (run command line: `behave` or `behave features/twitter.feature`) my promt shows the log above:

`Exception ImportError: No module named yaml
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/Library/Python/2.7/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/Library/Python/2.7/site-packages/behave/runner.py", line 677, in run_with_paths
    self.load_hooks()
  File "/Library/Python/2.7/site-packages/behave/runner.py", line 631, in load_hooks
    exec_file(hooks_path, self.hooks)
  File "/Library/Python/2.7/site-packages/behave/runner.py", line 304, in exec_file
    exec(code, globals, locals)
  File "features/environment.py", line 1, in <module>
    from yaml import load
ImportError: No module named yaml`

Any idea?

**Comment by onikiforov** [comment]
My fault, I didn't add `PyYAML` into requirements. Try to run `pip install pyyaml` and then rerun tests.
