### ISSUE TITLE
Observing SSL Error

### ISSUE THREAD

**Issue by sposavalike** [stanfy/behave-rest#7]
@search @twitter
  Scenario: Search for tweets                                         # features/twitter.feature:9
    Given I set base URL to "https://api.twitter.com/1.1"             # behave_rest/steps/__init__.py:13 0.003s
    And I set "Authorization" header to "context.twitter_auth"        # behave_rest/steps/__init__.py:36 0.000s
    When I make a GET request to "search/tweets.json" with parameters # behave_rest/steps/__init__.py:121 0.458s
      | q      |
      | stanfy |
      Traceback (most recent call last):
        File "/usr/lib/python2.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/lib/python2.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
          self.gen.throw(type, value, traceback)
        File "/usr/lib/python2.6/site-packages/behave/runner.py", line 454, in use_context_with_mode
          yield
        File "/usr/lib/python2.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "/root/behave-rest/behave_rest/steps/__init__.py", line 138, in request_with_parameters
          log_full(context.r)
        File "/root/behave-rest/behave_rest/steps/__init__.py", line 244, in log_full
          '\n'.join('{}: {}'.format(k, v) for k, v in req.headers.items()),
        File "/root/behave-rest/behave_rest/steps/__init__.py", line 244, in <genexpr>
          '\n'.join('{}: {}'.format(k, v) for k, v in req.headers.items()),
      ValueError: zero length field name in format

      Captured stdout:
Captured stderr:
      /usr/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:335: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
        SNIMissingWarning
      /usr/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:133: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
        InsecurePlatformWarning
      /usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
        InsecureRequestWarning)

    Then the response status code should equal 200                    # None
    And the response status code should be among 200, 201             # None
    And the response structure should equal "twitterSearchData"       # None
    And the response header "status" should equal "200 OK"            # None

Failing scenarios:
  features/twitter.feature:9  Search for tweets

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
2 steps passed, 1 failed, 4 skipped, 0 undefined
Took 0m0.461s

Am i missing anything, Could you please help?

**Comment by sposavalike** [comment]
Sorry my bad. It was due to setup issue.
