### ISSUE TITLE
Type Error 

### ISSUE THREAD

**Issue by sposavalike** [stanfy/behave-rest#8]
Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/lib/python2.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "/home/centos/behave-rest/behave_rest/steps/__init__.py", line 136, in request_with_parameters
          context.r = getattr(requests, request_verb.lower())(url, params, headers=context.headers, verify=context.verify_ssl)
      TypeError: get() takes exactly 1 argument (4 given)

Could you please help to resolve this?

**Comment by sposavalike** [comment]
Again issue with my request module. Sorry for the inconvenience.
